// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/hello/v1/hello.proto

package hello

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Hello struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Nome                 string   `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hello) Reset()         { *m = Hello{} }
func (m *Hello) String() string { return proto.CompactTextString(m) }
func (*Hello) ProtoMessage()    {}
func (*Hello) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4b701bf343e1e63, []int{0}
}

func (m *Hello) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hello.Unmarshal(m, b)
}
func (m *Hello) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hello.Marshal(b, m, deterministic)
}
func (m *Hello) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hello.Merge(m, src)
}
func (m *Hello) XXX_Size() int {
	return xxx_messageInfo_Hello.Size(m)
}
func (m *Hello) XXX_DiscardUnknown() {
	xxx_messageInfo_Hello.DiscardUnknown(m)
}

var xxx_messageInfo_Hello proto.InternalMessageInfo

func (m *Hello) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Hello) GetNome() string {
	if m != nil {
		return m.Nome
	}
	return ""
}

type HelloResponse struct {
	Resposta             string   `protobuf:"bytes,1,opt,name=resposta,proto3" json:"resposta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4b701bf343e1e63, []int{1}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetResposta() string {
	if m != nil {
		return m.Resposta
	}
	return ""
}

func init() {
	proto.RegisterType((*Hello)(nil), "Hello")
	proto.RegisterType((*HelloResponse)(nil), "HelloResponse")
}

func init() { proto.RegisterFile("protobuf/hello/v1/hello.proto", fileDescriptor_e4b701bf343e1e63) }

var fileDescriptor_e4b701bf343e1e63 = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0xcf, 0x48, 0xcd, 0xc9, 0xc9, 0xd7, 0x2f, 0x33, 0x84, 0x30, 0xf4,
	0xc0, 0xe2, 0x4a, 0xba, 0x5c, 0xac, 0x1e, 0x20, 0xae, 0x90, 0x00, 0x17, 0x73, 0x6e, 0x71, 0xba,
	0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x88, 0x29, 0x24, 0xc4, 0xc5, 0x92, 0x97, 0x9f, 0x9b,
	0x2a, 0xc1, 0x04, 0x16, 0x02, 0xb3, 0x95, 0xb4, 0xb9, 0x78, 0xc1, 0xca, 0x83, 0x52, 0x8b, 0x0b,
	0xf2, 0xf3, 0x8a, 0x53, 0x85, 0xa4, 0xb8, 0x38, 0x8a, 0x40, 0xec, 0xe2, 0x92, 0x44, 0xa8, 0x5e,
	0x38, 0xdf, 0xc8, 0x94, 0x8b, 0x07, 0xac, 0x38, 0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55, 0x48,
	0x95, 0x8b, 0xdb, 0xb9, 0x28, 0x35, 0xb1, 0x24, 0x15, 0x62, 0x23, 0x9b, 0x1e, 0x98, 0x96, 0xe2,
	0xd3, 0x43, 0x31, 0xd2, 0x49, 0x31, 0x4a, 0x3e, 0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39,
	0x3f, 0x57, 0xbf, 0x20, 0x27, 0xb1, 0x32, 0xbd, 0x28, 0xbf, 0x34, 0x2f, 0x05, 0xcc, 0x05, 0xbb,
	0x3d, 0x89, 0x0d, 0xec, 0x78, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0a, 0x7b, 0x7d, 0x58,
	0xdd, 0x00, 0x00, 0x00,
}
